# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Tests targeting low-coverage modules to increase overall line coverage."""
# AI-assisted unit test generated by Claude Code

import gzip
import json
import os
import re
import tempfile
import unittest
import warnings
from unittest.mock import Mock, patch

import numpy as np
import pandas as pd
from hta.common.trace_df import (
    find_events_by_name_patterns_using_decoded_names,
    find_events_by_name_patterns_using_symbol_table,
    find_op_occurrence,
    get_iterations,
)
from hta.common.trace_filter import (
    CompositeFilter,
    CPUOperatorFilter,
    FirstIterationFilter,
    GPUKernelFilter,
    IterationFilter,
    IterationIndexFilter,
    MemCopyEventFilter,
    NameFilter,
    NameIdColumnFilter,
    NameStringColumnFilter,
    RankFilter,
    TimeRangeFilter,
    ZeroDurationFilter,
)
from hta.common.trace_symbol_table import TraceSymbolTable
from hta.common.types import (
    DeviceType,
    GroupingPattern,
    infer_device_type,
    to_grouping_pattern,
)
from hta.utils.checker import is_valid_directory, OperationOutcome
from hta.utils.test_utils import get_test_data_dir


# ---- checker.py tests ----


class TestChecker(unittest.TestCase):
    def test_valid_readable_directory(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            result = is_valid_directory(d)
            self.assertTrue(result.success)
            self.assertEqual(result.reason, "")

    def test_valid_writable_directory(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            result = is_valid_directory(d, must_be_writable=True)
            self.assertTrue(result.success)

    def test_empty_path(self) -> None:
        result = is_valid_directory("")
        self.assertFalse(result.success)
        self.assertIn("non-empty string", result.reason)

    def test_nonexistent_path(self) -> None:
        result = is_valid_directory("/nonexistent_path_xyz_12345")
        self.assertFalse(result.success)
        self.assertIn("does not exist", result.reason)

    def test_file_not_directory(self) -> None:
        with tempfile.NamedTemporaryFile() as f:
            result = is_valid_directory(f.name)
            self.assertFalse(result.success)
            self.assertIn("not a directory", result.reason)

    def test_operation_outcome_dataclass(self) -> None:
        outcome = OperationOutcome(success=True, reason="ok")
        self.assertTrue(outcome.success)
        self.assertEqual(outcome.reason, "ok")


# ---- trace_df.py tests ----


class TestGetIterations(unittest.TestCase):
    def test_no_iteration_column(self) -> None:
        df = pd.DataFrame({"a": [1, 2, 3]})
        with self.assertRaises(TypeError):
            get_iterations(df)

    def test_non_integer_iteration_column(self) -> None:
        df = pd.DataFrame({"iteration": ["a", "b"]})
        with self.assertRaises(TypeError):
            get_iterations(df)

    def test_valid_iterations(self) -> None:
        df = pd.DataFrame({"iteration": [1, 2, 3, 1, 2]})
        result = get_iterations(df)
        self.assertEqual(result, [1, 2, 3])

    def test_iterations_with_minus_one(self) -> None:
        df = pd.DataFrame({"iteration": [-1, 1, 2]})
        result = get_iterations(df)
        self.assertEqual(result, [1, 2])


class TestFindOpOccurrence(unittest.TestCase):
    def test_empty_df(self) -> None:
        found, series = find_op_occurrence(pd.DataFrame(), "op", 0)
        self.assertFalse(found)

    def test_missing_columns(self) -> None:
        df = pd.DataFrame({"a": [1]})
        found, series = find_op_occurrence(df, "op", 0)
        self.assertFalse(found)

    def test_find_first_occurrence(self) -> None:
        df = pd.DataFrame(
            {"s_name": ["op_a", "op_b", "op_a"], "ts": [10, 20, 30], "index": [0, 1, 2]}
        )
        found, series = find_op_occurrence(df, "op_a", 0)
        self.assertTrue(found)
        self.assertEqual(series["ts"], 10)

    def test_find_last_occurrence(self) -> None:
        df = pd.DataFrame(
            {"s_name": ["op_a", "op_b", "op_a"], "ts": [10, 20, 30], "index": [0, 1, 2]}
        )
        found, series = find_op_occurrence(df, "op_a", -1)
        self.assertTrue(found)
        self.assertEqual(series["ts"], 30)

    def test_no_match(self) -> None:
        df = pd.DataFrame({"s_name": ["op_a"], "ts": [10], "index": [0]})
        found, series = find_op_occurrence(df, "op_z", 0)
        self.assertFalse(found)

    def test_out_of_range_position(self) -> None:
        df = pd.DataFrame({"s_name": ["op_a"], "ts": [10], "index": [0]})
        found, series = find_op_occurrence(df, "op_a", 5)
        self.assertFalse(found)


class TestFindEventsByNamePatterns(unittest.TestCase):
    def test_using_decoded_names(self) -> None:
        df = pd.DataFrame(
            {"s_name": ["aten::mm", "nccl::send", "aten::add"], "index": [0, 1, 2]}
        )
        indices = find_events_by_name_patterns_using_decoded_names(df, ["aten::.*"])
        self.assertEqual(sorted(indices.tolist()), [0, 2])

    def test_using_symbol_table(self) -> None:
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "nccl::send", "aten::add"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame(
            {
                "name": [
                    sym_id_map["aten::mm"],
                    sym_id_map["nccl::send"],
                    sym_id_map["aten::add"],
                ],
                "index": [0, 1, 2],
            }
        )
        indices = find_events_by_name_patterns_using_symbol_table(
            df, ["aten::.*"], sym_table
        )
        self.assertEqual(sorted(indices.tolist()), [0, 2])


# ---- types.py tests ----


class TestInferDeviceType(unittest.TestCase):
    def test_gpu_stream_only(self) -> None:
        df = pd.DataFrame({"stream": [1, 2, 3]})
        self.assertEqual(infer_device_type(df), DeviceType.GPU)

    def test_cpu_stream_only(self) -> None:
        df = pd.DataFrame({"stream": [-1, -1]})
        self.assertEqual(infer_device_type(df), DeviceType.CPU)

    def test_gpu_with_pid_tid(self) -> None:
        df = pd.DataFrame({"stream": [1, 2], "pid": [0, 0], "tid": [0, 0]})
        self.assertEqual(infer_device_type(df), DeviceType.GPU)

    def test_cpu_with_pid_tid(self) -> None:
        df = pd.DataFrame({"stream": [-1, -1], "pid": [123, 123], "tid": [456, 456]})
        self.assertEqual(infer_device_type(df), DeviceType.CPU)

    def test_unknown_mixed(self) -> None:
        df = pd.DataFrame({"stream": [-1, 1], "pid": [123, 123], "tid": [456, 456]})
        self.assertEqual(infer_device_type(df), DeviceType.UNKNOWN)


class TestGroupingPattern(unittest.TestCase):
    def test_match(self) -> None:
        gp = GroupingPattern(pattern=re.compile(r"aten::.*"))
        self.assertTrue(gp.match("aten::mm"))
        self.assertFalse(gp.match("nccl::send"))

    def test_inverse_match(self) -> None:
        gp = GroupingPattern(pattern=re.compile(r"aten::.*"), inverse_match=True)
        self.assertFalse(gp.match("aten::mm"))
        self.assertTrue(gp.match("nccl::send"))

    def test_hash(self) -> None:
        gp1 = GroupingPattern(pattern=re.compile(r"aten::.*"))
        gp2 = GroupingPattern(pattern=re.compile(r"aten::.*"))
        self.assertEqual(hash(gp1), hash(gp2))


class TestToGroupingPattern(unittest.TestCase):
    def test_from_string(self) -> None:
        gp = to_grouping_pattern("aten::.*", group_name="test")
        self.assertEqual(gp.group_name, "test")
        self.assertTrue(gp.match("aten::mm"))

    def test_from_list(self) -> None:
        gp = to_grouping_pattern(["aten::.*", "nccl::.*"])
        self.assertTrue(gp.match("aten::mm"))
        self.assertTrue(gp.match("nccl::send"))

    def test_from_compiled_regex(self) -> None:
        gp = to_grouping_pattern(re.compile(r"aten::.*"))
        self.assertTrue(gp.match("aten::mm"))

    def test_from_grouping_pattern(self) -> None:
        orig = GroupingPattern(pattern=re.compile(r"test"))
        result = to_grouping_pattern(orig)
        self.assertIs(result, orig)

    def test_invalid_type(self) -> None:
        with self.assertRaises(ValueError):
            to_grouping_pattern(123)  # type: ignore[arg-type]


# ---- trace_filter.py tests ----


class TestIterationFilter(unittest.TestCase):
    def test_single_iteration(self) -> None:
        df = pd.DataFrame({"iteration": [1, 2, 3, 1]})
        f = IterationFilter(1)
        result = f(df)
        self.assertEqual(len(result), 2)

    def test_list_iterations(self) -> None:
        df = pd.DataFrame({"iteration": [1, 2, 3]})
        f = IterationFilter([1, 3])
        result = f(df)
        self.assertEqual(len(result), 2)

    def test_no_iteration_column(self) -> None:
        df = pd.DataFrame({"a": [1, 2]})
        f = IterationFilter(1)
        result = f(df)
        self.assertEqual(len(result), 2)  # returns original df

    def test_invalid_type(self) -> None:
        with self.assertRaises(TypeError):
            IterationFilter("bad")  # type: ignore[arg-type]


class TestIterationIndexFilter(unittest.TestCase):
    def test_select_first(self) -> None:
        df = pd.DataFrame({"iteration": [10, 20, 10, 20]})
        f = IterationIndexFilter(0)
        result = f(df)
        self.assertTrue(all(result["iteration"] == 10))

    def test_no_iteration_column(self) -> None:
        df = pd.DataFrame({"a": [1]})
        f = IterationIndexFilter(0)
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_only_minus_one(self) -> None:
        df = pd.DataFrame({"iteration": [-1, -1]})
        f = IterationIndexFilter(0)
        result = f(df)
        self.assertEqual(len(result), 2)  # returns full df

    def test_skip_minus_one(self) -> None:
        df = pd.DataFrame({"iteration": [-1, 10, 20]})
        f = IterationIndexFilter(0)
        result = f(df)
        self.assertTrue(all(result["iteration"] == 10))

    def test_out_of_range_index(self) -> None:
        df = pd.DataFrame({"iteration": [10]})
        f = IterationIndexFilter(5)
        result = f(df)
        self.assertTrue(result.empty)

    def test_invalid_type(self) -> None:
        with self.assertRaises(TypeError):
            IterationIndexFilter("bad")  # type: ignore[arg-type]


class TestFirstIterationFilter(unittest.TestCase):
    def test_selects_first(self) -> None:
        df = pd.DataFrame({"iteration": [10, 20, 10, 20]})
        f = FirstIterationFilter()
        result = f(df)
        self.assertTrue(all(result["iteration"] == 10))


class TestRankFilter(unittest.TestCase):
    def test_single_rank(self) -> None:
        df = pd.DataFrame({"rank": [0, 1, 2, 0]})
        f = RankFilter(0)
        result = f(df)
        self.assertEqual(len(result), 2)

    def test_no_rank_column(self) -> None:
        df = pd.DataFrame({"a": [1]})
        f = RankFilter(0)
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_invalid_type(self) -> None:
        with self.assertRaises(TypeError):
            RankFilter("bad")  # type: ignore[arg-type]


class TestTimeRangeFilter(unittest.TestCase):
    def test_filter_in_range(self) -> None:
        df = pd.DataFrame({"ts": [10, 20, 30], "dur": [5, 5, 5]})
        f = TimeRangeFilter((10, 35))
        result = f(df)
        self.assertEqual(len(result), 3)

    def test_filter_excludes_out_of_range(self) -> None:
        df = pd.DataFrame({"ts": [10, 20, 30], "dur": [5, 5, 10]})
        f = TimeRangeFilter((10, 35))
        result = f(df)
        self.assertEqual(len(result), 2)  # last event ends at 40 > 35

    def test_no_ts_column(self) -> None:
        df = pd.DataFrame({"a": [1]})
        f = TimeRangeFilter((0, 100))
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_invalid_range(self) -> None:
        with self.assertRaises(ValueError):
            TimeRangeFilter((100, 10))

    def test_invalid_type(self) -> None:
        with self.assertRaises(ValueError):
            TimeRangeFilter("bad")  # type: ignore[arg-type]


class TestNameStringColumnFilter(unittest.TestCase):
    def test_match_s_name(self) -> None:
        df = pd.DataFrame({"s_name": ["aten::mm", "nccl::send", "aten::add"]})
        f = NameStringColumnFilter("aten::.*")
        result = f(df)
        self.assertEqual(len(result), 2)

    def test_no_string_name_column(self) -> None:
        df = pd.DataFrame({"name": [1, 2, 3]})
        f = NameStringColumnFilter("aten::.*")
        result = f(df)
        self.assertEqual(len(result), 3)  # returns original


class TestNameIdColumnFilter(unittest.TestCase):
    def test_with_symbol_table(self) -> None:
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "nccl::send"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame({"name": [sym_id_map["aten::mm"], sym_id_map["nccl::send"]]})
        f = NameIdColumnFilter("aten::.*")
        result = f(df, sym_table)
        self.assertEqual(len(result), 1)

    def test_without_symbol_table(self) -> None:
        df = pd.DataFrame({"name": [1, 2]})
        f = NameIdColumnFilter("aten::.*")
        result = f(df, None)
        self.assertEqual(len(result), 2)  # returns original


class TestNameFilter(unittest.TestCase):
    def test_with_string_names(self) -> None:
        df = pd.DataFrame({"s_name": ["aten::mm", "nccl::send"]})
        f = NameFilter("aten::.*")
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_empty_df(self) -> None:
        f = NameFilter("aten::.*")
        result = f(pd.DataFrame())
        self.assertTrue(result.empty)

    def test_with_constructor_symbol_table(self) -> None:
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "nccl::send"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame({"name": [sym_id_map["aten::mm"], sym_id_map["nccl::send"]]})
        f = NameFilter("aten::.*", symbol_table=sym_table)
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_with_callsite_symbol_table(self) -> None:
        """When symbol_table is passed at call site, it takes precedence."""
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "nccl::send"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame({"name": [sym_id_map["aten::mm"], sym_id_map["nccl::send"]]})
        f = NameFilter("aten::.*")
        result = f(df, symbol_table=sym_table)
        self.assertEqual(len(result), 1)


class TestQueryFilter(unittest.TestCase):
    def test_basic_query(self) -> None:
        df = pd.DataFrame({"dur": [0, 5, 10]})
        result = ZeroDurationFilter(df)
        self.assertEqual(len(result), 2)


class TestGPUKernelFilter(unittest.TestCase):
    def test_no_stream_column(self) -> None:
        df = pd.DataFrame({"a": [1]})
        f = GPUKernelFilter()
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_without_symbol_table(self) -> None:
        df = pd.DataFrame({"stream": [1, -1, 2], "correlation": [1, 1, 1]})
        f = GPUKernelFilter()
        result = f(df)
        self.assertEqual(len(result), 2)


class TestCPUOperatorFilter(unittest.TestCase):
    def test_no_stream_column(self) -> None:
        df = pd.DataFrame({"a": [1]})
        f = CPUOperatorFilter()
        result = f(df)
        self.assertEqual(len(result), 1)

    def test_without_symbol_table(self) -> None:
        df = pd.DataFrame({"stream": [1, -1, 2], "correlation": [1, 1, 1]})
        f = CPUOperatorFilter()
        result = f(df)
        self.assertEqual(len(result), 1)


class TestCompositeFilter(unittest.TestCase):
    def test_chain_filters(self) -> None:
        df = pd.DataFrame({"iteration": [1, 2, 3], "rank": [0, 0, 1]})
        f = CompositeFilter([IterationFilter([1, 2]), RankFilter(0)])
        result = f(df)
        self.assertEqual(len(result), 2)

    def test_invalid_filter(self) -> None:
        with self.assertRaises(TypeError):
            CompositeFilter(["not a filter"])  # type: ignore[list-item]

    def test_self_reference(self) -> None:
        # CompositeFilter checks if any filter is self
        f = CompositeFilter.__new__(CompositeFilter)
        with self.assertRaises(ValueError):
            CompositeFilter.__init__(f, [f])


class TestMemCopyEventFilter(unittest.TestCase):
    def test_empty_df(self) -> None:
        f = MemCopyEventFilter("Memcpy HtoD")
        result = f(pd.DataFrame())
        self.assertTrue(result.empty)

    def test_with_symbol_table(self) -> None:
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["Memcpy HtoD", "gpu_memcpy", "aten::mm", "kernel"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame(
            {
                "name": [sym_id_map["Memcpy HtoD"], sym_id_map["aten::mm"]],
                "cat": [sym_id_map["gpu_memcpy"], sym_id_map["kernel"]],
            }
        )
        f = MemCopyEventFilter("Memcpy HtoD")
        result = f(df, sym_table)
        self.assertEqual(len(result), 1)

    def test_unknown_memory_copy_type(self) -> None:
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm"])
        df = pd.DataFrame({"name": [0], "cat": [0]})
        f = MemCopyEventFilter("nonexistent_type")
        result = f(df, sym_table)
        self.assertTrue(result.empty)

    def test_with_constructor_symbol_table(self) -> None:
        """When symbol_table is passed via constructor, it is used."""
        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["Memcpy HtoD", "gpu_memcpy"])
        sym_id_map = sym_table.get_sym_id_map()
        df = pd.DataFrame(
            {
                "name": [sym_id_map["Memcpy HtoD"]],
                "cat": [sym_id_map["gpu_memcpy"]],
            }
        )
        f = MemCopyEventFilter("Memcpy HtoD", symbol_table=sym_table)
        result = f(df)  # no symbol_table at call site
        self.assertEqual(len(result), 1)


# ---- analyzers/timeline.py tests ----


class TestAnalyzersTimeline(unittest.TestCase):
    def test_get_unique_values(self) -> None:
        from hta.analyzers.timeline import _get_unique_values

        df = pd.DataFrame({"stream": [-1, 0, 1, 2, -1]})
        result = _get_unique_values(df, "stream")
        self.assertEqual(result, [0, 1, 2])

    def test_get_unique_values_missing_column(self) -> None:
        from hta.analyzers.timeline import _get_unique_values

        df = pd.DataFrame({"a": [1]})
        with self.assertRaises(ValueError):
            _get_unique_values(df, "stream")

    def test_simplify_name_old(self) -> None:
        from hta.analyzers.timeline import _simplify_name

        self.assertEqual(_simplify_name("aten::mm"), "aten::mm")
        result = _simplify_name("autograd::engine::evaluate_function: TBackward0")
        self.assertNotIn("autograd::engine::evaluate_function", result)

    def test_prepare_timeline_gpu_events_missing_columns(self) -> None:
        from hta.analyzers.timeline import prepare_timeline_gpu_events

        df = pd.DataFrame({"a": [1]})
        sym_table = TraceSymbolTable()
        with self.assertRaises(ValueError):
            prepare_timeline_gpu_events(df, sym_table)

    def test_plot_timeline_missing_columns(self) -> None:
        from hta.analyzers.timeline import plot_timeline

        df = pd.DataFrame({"a": [1]})
        with self.assertRaises(ValueError):
            plot_timeline("test", df)


# ---- utils/utils.py tests ----


class TestUtilsFunctions(unittest.TestCase):
    def test_normalize_path_dot_prefix(self) -> None:
        from hta.utils.utils import normalize_path

        result = normalize_path("./subdir")
        self.assertTrue(result.endswith("subdir"))
        self.assertFalse(result.startswith("./"))

    def test_normalize_path_dot_only(self) -> None:
        from hta.utils.utils import normalize_path

        result = normalize_path("./")
        self.assertTrue(len(result) > 2)

    def test_normalize_path_tilde_prefix(self) -> None:
        from hta.utils.utils import normalize_path

        result = normalize_path("~/subdir")
        self.assertFalse(result.startswith("~/"))

    def test_normalize_path_tilde_only(self) -> None:
        from hta.utils.utils import normalize_path

        result = normalize_path("~/")
        self.assertTrue(len(result) > 2)

    def test_normalize_path_absolute(self) -> None:
        from hta.utils.utils import normalize_path

        result = normalize_path("/tmp/test")
        self.assertEqual(result, "/tmp/test")

    def test_is_computer_kernel_deprecated(self) -> None:
        from hta.utils.utils import is_computer_kernel

        # is_computer_kernel is deprecated alias for is_compute_kernel
        self.assertTrue(is_computer_kernel("custom_gemm_kernel"))

    def test_get_memory_kernel_type(self) -> None:
        from hta.utils.utils import get_memory_kernel_type

        self.assertEqual(get_memory_kernel_type("Memcpy DtoH (Device)"), "Memcpy DtoH")
        self.assertEqual(get_memory_kernel_type("Memcpy HtoD (Pinned)"), "Memcpy HtoD")
        self.assertEqual(get_memory_kernel_type("Memset (Device)"), "Memset")
        self.assertEqual(get_memory_kernel_type("custom_dma_op"), "Memcpy Unknown")

    def test_normalize_gpu_stream_numbers(self) -> None:
        from hta.utils.utils import normalize_gpu_stream_numbers

        df = pd.DataFrame({"stream": [1, "2", None, "abc"]})
        normalize_gpu_stream_numbers(df)
        self.assertEqual(df["stream"].tolist(), [1, 2, -1, -1])

    def test_normalize_gpu_stream_numbers_no_column(self) -> None:
        from hta.utils.utils import normalize_gpu_stream_numbers

        df = pd.DataFrame({"a": [1]})
        normalize_gpu_stream_numbers(df)  # should not raise

    def test_get_symbol_column_names(self) -> None:
        from hta.utils.utils import get_symbol_column_names

        df = pd.DataFrame({"s_name": ["a"], "s_cat": ["b"]})
        name_col, cat_col = get_symbol_column_names(df)
        self.assertEqual(name_col, "s_name")
        self.assertEqual(cat_col, "s_cat")

    def test_get_symbol_column_names_no_symbol_cols(self) -> None:
        from hta.utils.utils import get_symbol_column_names

        df = pd.DataFrame({"name": [1], "cat": [2]})
        name_col, cat_col = get_symbol_column_names(df)
        # Falls back to empty or name/cat
        self.assertIn(name_col, ["", "name"])

    def test_get_kernel_type_other(self) -> None:
        from hta.utils.utils import get_kernel_type

        # A name that matches none of the kernel type patterns
        result = get_kernel_type("cudaDeviceSynchronize")
        self.assertEqual(result, "OTHER")

    def test_get_kernel_type_communication(self) -> None:
        from hta.utils.utils import get_kernel_type

        result = get_kernel_type("nccl:all_reduce")
        self.assertEqual(result, "COMMUNICATION")

    def test_get_kernel_type_memory(self) -> None:
        from hta.utils.utils import get_kernel_type

        result = get_kernel_type("Memcpy DtoH (Device)")
        self.assertEqual(result, "MEMORY")

    def test_get_kernel_type_computation(self) -> None:
        from hta.utils.utils import get_kernel_type

        result = get_kernel_type("custom_gemm_kernel")
        self.assertEqual(result, "COMPUTATION")


# ---- analyzers/timeline.py additional tests ----


class TestPrepareTimelineGPUEvents(unittest.TestCase):
    def test_prepare_with_valid_data(self) -> None:
        from hta.analyzers.timeline import prepare_timeline_gpu_events

        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "kernel", "nccl::send", "cpu_op"])
        sym_id_map = sym_table.get_sym_id_map()

        df = pd.DataFrame(
            {
                "iteration": [1, 1],
                "name": [sym_id_map["aten::mm"], sym_id_map["nccl::send"]],
                "cat": [sym_id_map["kernel"], sym_id_map["cpu_op"]],
                "rank": [0, 0],
                "stream": [7, 7],
                "ts": [1000, 2000],
                "dur": [500, 100],
            }
        )

        result = prepare_timeline_gpu_events(df, sym_table)
        self.assertFalse(result.empty)
        self.assertIn("calibrated_start_global", result.columns)
        self.assertIn("calibrated_end_global", result.columns)
        self.assertIn("task", result.columns)
        self.assertIn("label", result.columns)

    def test_prepare_with_explicit_filters(self) -> None:
        from hta.analyzers.timeline import prepare_timeline_gpu_events

        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["aten::mm", "kernel"])
        sym_id_map = sym_table.get_sym_id_map()

        df = pd.DataFrame(
            {
                "iteration": [1, 2],
                "name": [sym_id_map["aten::mm"], sym_id_map["aten::mm"]],
                "cat": [sym_id_map["kernel"], sym_id_map["kernel"]],
                "rank": [0, 1],
                "stream": [7, 8],
                "ts": [1000, 2000],
                "dur": [500, 100],
            }
        )

        result = prepare_timeline_gpu_events(
            df, sym_table, ranks=[0], iterations=[1], streams=[7]
        )
        self.assertEqual(len(result), 1)

    @patch("hta.analyzers.timeline.px.timeline")
    def test_plot_timeline_with_ranks(self, mock_px_timeline: Mock) -> None:
        from hta.analyzers.timeline import plot_timeline

        mock_fig = Mock()
        mock_px_timeline.return_value = mock_fig

        df = pd.DataFrame(
            {
                "calibrated_start_global": pd.to_datetime([1000, 2000], unit="us"),
                "calibrated_end_global": pd.to_datetime([1500, 2500], unit="us"),
                "task": ["rank 0 stream 7", "rank 0 stream 7"],
                "label": ["op_a", "op_b"],
                "rank": [0, 0],
            }
        )
        plot_timeline("test", df, ranks=[0])
        mock_px_timeline.assert_called_once()

    @patch("hta.analyzers.timeline.px.timeline")
    def test_plot_timeline_no_rank_column(self, mock_px_timeline: Mock) -> None:
        from hta.analyzers.timeline import plot_timeline

        mock_fig = Mock()
        mock_px_timeline.return_value = mock_fig

        df = pd.DataFrame(
            {
                "calibrated_start_global": pd.to_datetime([1000], unit="us"),
                "calibrated_end_global": pd.to_datetime([1500], unit="us"),
                "task": ["task1"],
                "label": ["op_a"],
            }
        )
        plot_timeline("test", df)
        mock_px_timeline.assert_called_once()


# ---- trace_file.py additional tests ----


class TestTraceFileAdditional(unittest.TestCase):
    def test_create_rank_to_trace_dict_from_list(self) -> None:
        from hta.common.trace_file import create_rank_to_trace_dict

        data_dir = get_test_data_dir()
        trace_file = os.path.join(
            data_dir, "trace_file_list", "inference_rank_1.json.gz"
        )
        ok, result = create_rank_to_trace_dict([trace_file])
        self.assertTrue(ok)

    def test_read_write_json(self) -> None:
        """Test read_trace/write_trace with plain .json files (not .gz)."""
        from hta.common.trace_file import read_trace, write_trace

        test_data = {"traceEvents": [{"name": "test", "ph": "X"}]}
        with tempfile.TemporaryDirectory() as d:
            json_path = os.path.join(d, "test.json")
            write_trace(test_data, json_path)
            result = read_trace(json_path)
            self.assertEqual(result, test_data)

    def test_read_trace_invalid_extension(self) -> None:
        from hta.common.trace_file import read_trace

        with self.assertRaises(ValueError):
            read_trace("/tmp/test.txt")

    def test_write_trace_creates_directory(self) -> None:
        from hta.common.trace_file import write_trace

        with tempfile.TemporaryDirectory() as d:
            nested_path = os.path.join(d, "subdir", "test.json")
            write_trace({"data": 1}, nested_path)
            self.assertTrue(os.path.exists(nested_path))

    def test_update_trace_rank_no_distributed_info(self) -> None:
        """Test update_trace_rank when distributedInfo key doesn't exist."""
        from hta.common.trace_file import read_trace, update_trace_rank, write_trace

        test_data: dict[str, list[str]] = {"traceEvents": []}
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "test.json.gz")
            write_trace(test_data, path)
            update_trace_rank(path, 42)
            result = read_trace(path)
            self.assertEqual(result["distributedInfo"]["rank"], 42)


class TestCheckerNotWritable(unittest.TestCase):
    def test_not_writable_directory(self) -> None:
        """Test is_valid_directory with must_be_writable on a read-only dir."""
        with tempfile.TemporaryDirectory() as d:
            read_only = os.path.join(d, "readonly")
            os.makedirs(read_only)
            os.chmod(read_only, 0o444)
            try:
                result = is_valid_directory(read_only, must_be_writable=True)
                self.assertFalse(result.success)
                self.assertIn("not writable", result.reason)
            finally:
                os.chmod(read_only, 0o755)


class TestDataProvider(unittest.TestCase):
    def test_data_provider_with_tuple(self) -> None:
        from hta.utils.test_utils import data_provider

        results = []

        @data_provider(lambda: [(1, 2), (3, 4)])
        def sample_test(self, a, b):
            results.append((a, b))

        sample_test(self)
        self.assertEqual(results, [(1, 2), (3, 4)])

    def test_data_provider_with_dict(self) -> None:
        from hta.utils.test_utils import data_provider

        results = []

        @data_provider(lambda: [{"val": 10}, {"val": 20}])
        def sample_test(self, val=0):
            results.append(val)

        sample_test(self)
        self.assertEqual(results, [10, 20])

    def test_data_provider_with_scalar(self) -> None:
        from hta.utils.test_utils import data_provider

        results = []

        @data_provider(lambda: [1, 2, 3])
        def sample_test(self, val):
            results.append(val)

        sample_test(self)
        self.assertEqual(results, [1, 2, 3])


class TestDefaultValues(unittest.TestCase):
    def test_yaml_version_invalid_string(self) -> None:
        from hta.configs.default_values import YamlVersion

        with self.assertRaises(ValueError):
            YamlVersion.from_string("invalid")

    def test_attribute_spec_eq_non_attribute(self) -> None:
        from hta.configs.default_values import AttributeSpec, ValueType, YamlVersion

        spec = AttributeSpec(
            name="test",
            raw_name="test_raw",
            value_type=ValueType.String,
            default_value="",
            min_supported_version=YamlVersion(1, 0, 0),
        )
        self.assertNotEqual(spec, "not an AttributeSpec")


# ---- common/trace.py tests ----


def _vt_trace_dir() -> str:
    """Return the vision_transformer trace directory for tests that need real traces."""
    return get_test_data_dir("vision_transformer")


def _inference_trace_dir() -> str:
    """Return the inference_single_rank trace directory."""
    return get_test_data_dir("inference_single_rank")


class TestTransformCorrelationToIndex(unittest.TestCase):
    # AI-assisted test
    def test_no_correlation_column(self) -> None:
        """Line 111-112: early return when 'correlation' not in df.columns."""
        from hta.common.trace import transform_correlation_to_index

        df = pd.DataFrame({"index": [0, 1], "stream": [7, -1], "name": [0, 1]})
        sym_table = TraceSymbolTable()
        result = transform_correlation_to_index(df, sym_table)
        self.assertNotIn("index_correlation", result.columns)


class TestParseTraceFileValidation(unittest.TestCase):
    # AI-assisted test
    def test_invalid_file_extension(self) -> None:
        """Line 250: ValueError for files not ending in .gz or .json."""
        from hta.common.trace import parse_trace_file

        with self.assertRaises(ValueError) as ctx:
            parse_trace_file("/tmp/trace.txt")
        self.assertIn(".gz", str(ctx.exception))


class TestAddFwdBwdLinks(unittest.TestCase):
    # AI-assisted test
    def test_with_fwdbwd_events(self) -> None:
        """Lines 292-335: cover the full fwdbwd linking logic."""
        from hta.common.trace import add_fwd_bwd_links

        df = pd.DataFrame(
            {
                "index": [0, 1, 2, 3],
                "cat": ["cpu_op", "cpu_op", "fwdbwd", "fwdbwd"],
                "ts": [100, 200, 100, 200],
                "dur": [50, 50, 0, 0],
                "tid": [1, 1, 1, 1],
                "pid": [10, 10, 10, 10],
                "ph": ["X", "X", "s", "f"],
                "id": [0, 0, 99, 99],
                "bp": ["", "", "", "e"],
                "stream": [-1, -1, -1, -1],
            }
        )
        add_fwd_bwd_links(df)
        self.assertIn("fwdbwd_index", df.columns)
        self.assertIn("fwdbwd", df.columns)
        self.assertNotIn("key", df.columns)

    def test_empty_fwdbwd_start_or_end(self) -> None:
        """Line 318: early return when start or end events are empty after merge."""
        from hta.common.trace import add_fwd_bwd_links

        df = pd.DataFrame(
            {
                "index": [0, 1],
                "cat": ["fwdbwd", "fwdbwd"],
                "ts": [100, 200],
                "dur": [0, 0],
                "tid": [1, 1],
                "pid": [10, 10],
                "ph": ["s", "f"],
                "id": [99, 99],
                "bp": ["", "e"],
                "stream": [-1, -1],
            }
        )
        add_fwd_bwd_links(df)
        if "fwdbwd_index" in df.columns:
            self.assertTrue(all(df["fwdbwd_index"] == -1))

    def test_no_fwdbwd_events(self) -> None:
        """Line 289-290: early return when no fwdbwd events."""
        from hta.common.trace import add_fwd_bwd_links

        df = pd.DataFrame(
            {
                "index": [0, 1],
                "cat": ["cpu_op", "cpu_op"],
                "ts": [100, 200],
                "dur": [50, 50],
            }
        )
        add_fwd_bwd_links(df)
        self.assertNotIn("fwdbwd_index", df.columns)


class TestTraceInit(unittest.TestCase):
    # AI-assisted test
    def test_init_with_list_trace_files(self) -> None:
        """Lines 390-392: trace_files as list path."""
        from hta.common.trace import Trace

        data_dir = get_test_data_dir()
        trace_file = os.path.join(
            data_dir, "trace_file_list", "inference_rank_1.json.gz"
        )
        t = Trace(trace_dir=data_dir, trace_files=[trace_file])
        self.assertIn(1, t.trace_files)

    def test_init_with_unsupported_trace_files_type(self) -> None:
        """Lines 393-397: unsupported trace_files type logs error and returns early."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir, trace_files=42)  # type: ignore[arg-type]
        # 'return' at line 397 exits before traces/symbol_table are initialized
        self.assertFalse(hasattr(t, "traces"))

    def test_load_traces_already_parsed(self) -> None:
        """Lines 421-423: early return when traces already parsed."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.is_parsed = True
        t.load_traces()
        self.assertTrue(t.is_parsed)

    def test_parse_single_rank(self) -> None:
        """Lines 435-457: parse a single rank."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        ranks = sorted(t.trace_files.keys())
        if ranks:
            t.parse_single_rank(ranks[0])
            self.assertIn(ranks[0], t.traces)

    def test_parse_traces_empty_ranks(self) -> None:
        """Lines 560-562: empty list of ranks to parse."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.trace_files = {}
        t.parse_traces()
        self.assertFalse(t.is_parsed)

    def test_get_trace_invalid_rank(self) -> None:
        """Lines 632-634: ValueError when rank not in traces."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        with self.assertRaises(ValueError):
            t.get_trace(999)

    def test_get_raw_trace_invalid_rank(self) -> None:
        """Lines 659-661: ValueError when rank not in trace_files."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        with self.assertRaises(ValueError):
            t.get_raw_trace_for_one_rank(999)

    def test_normalize_trace_filenames_invalid_type(self) -> None:
        """Lines 673-679: ValueError when trace_files is not a dict."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.trace_files = "not_a_dict"  # type: ignore[assignment]
        with self.assertRaises(ValueError):
            t._normalize_trace_filenames()

    def test_normalize_trace_filenames_relative_paths(self) -> None:
        """Lines 681-684: normalize relative filenames."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        rank = next(iter(t.trace_files))
        t.trace_files[rank] = "relative_file.json.gz"
        t._normalize_trace_filenames()
        self.assertTrue(t.trace_files[rank].startswith(t.trace_path))

    def test_validate_trace_files_missing_file(self) -> None:
        """Lines 693-698: validation fails for nonexistent file."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.trace_files[999] = "/nonexistent/path/trace.json.gz"
        self.assertFalse(t._validate_trace_files())

    def test_validate_trace_files_bad_extension(self) -> None:
        """Lines 699-703: validation fails for bad file extension."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        with tempfile.NamedTemporaryFile(suffix=".txt") as f:
            t.trace_files = {0: f.name}
            self.assertFalse(t._validate_trace_files())


class TestTraceWriteAndConvert(unittest.TestCase):
    # AI-assisted test
    def test_write_raw_trace(self) -> None:
        """Lines 665-667: write_raw_trace gzip output."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        contents = {"traceEvents": [{"name": "test"}]}
        with tempfile.TemporaryDirectory() as d:
            out_path = os.path.join(d, "output.json.gz")
            t.write_raw_trace(out_path, contents)
            self.assertTrue(os.path.exists(out_path))
            with gzip.open(out_path, "rt") as fp:
                loaded = json.load(fp)
            self.assertEqual(loaded, contents)

    def test_convert_time_series_missing_columns(self) -> None:
        """Lines 904-909: missing required columns returns empty list."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        series = pd.DataFrame({"foo": [1, 2]})
        result = t.convert_time_series_to_events(series, "counter", "value")
        self.assertEqual(result, [])

    def test_convert_time_series_with_name_and_id(self) -> None:
        """Lines 914-919: cover branches for 'name' and 'id' columns in series."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.min_ts = 0
        series = pd.DataFrame(
            {
                "pid": [1, 1],
                "ts": [100, 200],
                "value": [10, 20],
                "name": ["a", "b"],
                "id": [1, 2],
            }
        )
        result = t.convert_time_series_to_events(series, "counter", "value")
        self.assertEqual(len(result), 2)
        self.assertIn("id", result[0])
        self.assertEqual(result[0]["name"], "a")

    def test_convert_time_series_without_name(self) -> None:
        """Lines 916-917: 'name' column absent, uses counter_name."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.min_ts = 0
        series = pd.DataFrame({"pid": [1], "ts": [100], "value": [10]})
        result = t.convert_time_series_to_events(series, "my_counter", "value")
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0]["name"], "my_counter")


class TestTraceGetStartUnixtime(unittest.TestCase):
    # AI-assisted test
    def test_invalid_rank_raises(self) -> None:
        """Lines 966-969: ValueError when rank not in traces."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        with self.assertRaises(ValueError):
            t.get_trace_start_unixtime_ns(999)


class TestTraceFlowEvent(unittest.TestCase):
    # AI-assisted test
    def test_flow_event_start(self) -> None:
        """Lines 932-955: static flow_event method with is_start=True."""
        from hta.common.trace import Trace

        result = Trace.flow_event(
            id=1, pid=10, tid=20, ts=1000, is_start=True, name="test", cat="flow"
        )
        self.assertEqual(result["ph"], "s")
        self.assertNotIn("bp", result)
        self.assertNotIn("args", result)

    def test_flow_event_end_with_args(self) -> None:
        """Lines 932-955: flow_event with is_start=False and args."""
        from hta.common.trace import Trace

        result = Trace.flow_event(
            id=1,
            pid=10,
            tid=20,
            ts=1000,
            is_start=False,
            name="test",
            cat="flow",
            args={"key": "val"},
        )
        self.assertEqual(result["ph"], "f")
        self.assertEqual(result["bp"], "e")
        self.assertEqual(result["args"], {"key": "val"})


class TestTraceGetIterations(unittest.TestCase):
    # AI-assisted test
    def test_get_iterations_no_iteration_col(self) -> None:
        """Lines 597-604: return empty list when 'iteration' column missing."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.traces[0] = pd.DataFrame({"ts": [100], "dur": [50]})
        result = t.get_iterations(0)
        self.assertEqual(result, [])

    def test_get_iterations_invalid_rank(self) -> None:
        """Lines 597-604: return empty list when rank is invalid."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        result = t.get_iterations(999)
        self.assertEqual(result, [])


class TestTraceDecodeSymbolIds(unittest.TestCase):
    # AI-assisted test
    def test_decode_symbol_ids(self) -> None:
        """Lines 864-875: decode_symbol_ids method."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.parse_traces(max_ranks=1, use_multiprocessing=False)
        t.decode_symbol_ids(use_shorten_name=True)
        rank = t.get_ranks()[0]
        df = t.get_trace(rank)
        # After decoding, 's_name' column should contain strings
        self.assertIn("s_name", df.columns)
        self.assertIsInstance(df["s_name"].iloc[0], str)


class TestTraceFilterGpuKernels(unittest.TestCase):
    # AI-assisted test
    def test_filter_with_single_profiler_step(self) -> None:
        """Lines 848-854: skip filtering when only one profiler step."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.parse_traces(max_ranks=1, use_multiprocessing=False)
        original_len = len(t.traces[t.get_ranks()[0]])
        with patch.object(t.symbol_table, "get_profiler_step_ids", return_value=[999]):
            t._filter_irrelevant_gpu_kernels()
        self.assertEqual(len(t.traces[t.get_ranks()[0]]), original_len)

    def test_filter_with_no_profiler_steps(self) -> None:
        """Lines 841-847: skip filtering when no profiler steps."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.parse_traces(max_ranks=1, use_multiprocessing=False)
        original_len = len(t.traces[t.get_ranks()[0]])
        with patch.object(t.symbol_table, "get_profiler_step_ids", return_value=[]):
            t._filter_irrelevant_gpu_kernels()
        self.assertEqual(len(t.traces[t.get_ranks()[0]]), original_len)


class TestTraceFixMtiaMemoryKernels(unittest.TestCase):
    # AI-assisted test
    def test_fix_mtia_deprecation_warning(self) -> None:
        """Lines 731-733: deprecated _fix_mtia_memory_kernels."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.parse_traces(max_ranks=1, use_multiprocessing=False)
        rank = t.get_ranks()[0]
        df = t.traces[rank]
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            t._fix_mtia_memory_kernels(df)
            self.assertTrue(any(issubclass(x.category, DeprecationWarning) for x in w))


class TestTraceMtiaFilter(unittest.TestCase):
    # AI-assisted test
    def test_filter_mtia_device_type(self) -> None:
        """Lines 816-862: MTIA filtering path."""
        from hta.common.trace import Trace

        vt_dir = _vt_trace_dir()
        t = Trace(trace_dir=vt_dir)
        t.parse_traces(max_ranks=1, use_multiprocessing=False)
        with patch.object(t, "get_device_type", return_value="MTIA"):
            profiler_steps = t.symbol_table.get_profiler_step_ids()
            if len(profiler_steps) > 1:
                t._filter_irrelevant_gpu_kernels()


# ---- common/timeline.py tests ----


class TestCheckTimelineInput(unittest.TestCase):
    # AI-assisted test
    def test_empty_dataframe(self) -> None:
        """Lines 138-139: empty DataFrame returns False."""
        from hta.common.timeline import _check_timeline_input, TimelinePlotSetting

        setting = TimelinePlotSetting()
        result = _check_timeline_input(pd.DataFrame(), setting)
        self.assertFalse(result)

    def test_missing_required_columns(self) -> None:
        """Lines 148-151: missing required columns returns False."""
        from hta.common.timeline import _check_timeline_input, TimelinePlotSetting

        setting = TimelinePlotSetting()
        df = pd.DataFrame({"some_col": [1, 2]})
        result = _check_timeline_input(df, setting)
        self.assertFalse(result)


class TestSetTaskNames(unittest.TestCase):
    # AI-assisted test
    def test_multi_traces(self) -> None:
        """Lines 204-206: multi_traces branch."""
        from hta.common.timeline import _set_task_names, TimelinePlotSetting

        setting = TimelinePlotSetting(auto_detect=False, multi_traces=True)
        events = pd.DataFrame(
            {"trace": ["t1", "t2"], "stream": [7, 8], "ts": [100, 200]}
        )
        result = _set_task_names(events, setting)
        self.assertEqual(len(result), 2)

    def test_multi_ranks(self) -> None:
        """Lines 208-210: multi_ranks branch."""
        from hta.common.timeline import _set_task_names, TimelinePlotSetting

        setting = TimelinePlotSetting(
            auto_detect=False,
            multi_ranks=True,
            event_type=__import__(
                "hta.common.timeline", fromlist=["EventType"]
            ).EventType.AllEvents,
        )
        events = pd.DataFrame({"rank": [0, 1], "stream": [-1, 7], "ts": [100, 200]})
        result = _set_task_names(events, setting)
        self.assertEqual(len(result), 2)

    def test_cpu_events_with_tid_and_depth(self) -> None:
        """Lines 216-222: CPUEvents with tid and depth."""
        from hta.common.timeline import _set_task_names, EventType, TimelinePlotSetting

        setting = TimelinePlotSetting(
            auto_detect=False,
            event_type=EventType.CPUEvents,
            compress_threads=False,
        )
        events = pd.DataFrame(
            {"tid": [10, 20], "depth": [0, 1], "stream": [-1, -1], "ts": [100, 200]}
        )
        result = _set_task_names(events, setting)
        self.assertEqual(len(result), 2)

    def test_cpu_events_no_tid_no_depth(self) -> None:
        """Lines 223-224: CPUEvents with no tid/depth columns gives 'cpu events'."""
        from hta.common.timeline import _set_task_names, EventType, TimelinePlotSetting

        setting = TimelinePlotSetting(auto_detect=False, event_type=EventType.CPUEvents)
        events = pd.DataFrame({"stream": [-1, -1], "ts": [100, 200]})
        result = _set_task_names(events, setting)
        self.assertTrue(all("cpu events" in str(v) for v in result.values))

    def test_empty_tasks_raises(self) -> None:
        """Lines 229-232: NotImplementedError when no label columns."""
        from hta.common.timeline import _set_task_names, EventType, TimelinePlotSetting

        # Test the AllEvents path (line 226) which exercises _compute_label_row.
        setting2 = TimelinePlotSetting(
            auto_detect=False,
            event_type=EventType.AllEvents,
            multi_streams=False,
            multi_ranks=False,
            multi_traces=False,
        )
        events = pd.DataFrame({"stream": [-1, 7, 0], "ts": [100, 200, 300]})
        result = _set_task_names(events, setting2)
        self.assertEqual(len(result), 3)


class TestGetSortColumns(unittest.TestCase):
    # AI-assisted test
    def test_multi_traces(self) -> None:
        """Lines 238-239: multi_traces adds 'trace'."""
        from hta.common.timeline import _get_sort_columns, TimelinePlotSetting

        setting = TimelinePlotSetting(auto_detect=False, multi_traces=True)
        events = pd.DataFrame({"trace": ["t1"], "ts": [100]})
        result = _get_sort_columns(events, setting)
        self.assertIn("trace", result)

    def test_multi_ranks(self) -> None:
        """Lines 240-241: multi_ranks adds 'rank'."""
        from hta.common.timeline import _get_sort_columns, TimelinePlotSetting

        setting = TimelinePlotSetting(auto_detect=False, multi_ranks=True)
        events = pd.DataFrame({"rank": [0], "ts": [100]})
        result = _get_sort_columns(events, setting)
        self.assertIn("rank", result)

    def test_cpu_events_with_tid(self) -> None:
        """Lines 244-248: CPUEvents adds tid and depth."""
        from hta.common.timeline import (
            _get_sort_columns,
            EventType,
            TimelinePlotSetting,
        )

        setting = TimelinePlotSetting(auto_detect=False, event_type=EventType.CPUEvents)
        events = pd.DataFrame({"tid": [1], "depth": [0], "ts": [100]})
        result = _get_sort_columns(events, setting)
        self.assertIn("tid", result)
        self.assertIn("depth", result)


class TestAlignModuleWithKernels(unittest.TestCase):
    # AI-assisted test
    def test_missing_required_columns(self) -> None:
        """Lines 284-287: ValueError when required columns missing."""
        from hta.common.timeline import align_module_with_kernels

        df = pd.DataFrame({"name": ["op1"], "stream": [-1]})
        with self.assertRaises(ValueError):
            align_module_with_kernels(df, ["op1"])

    def test_with_s_name_column(self) -> None:
        """Lines 303-320: decoded names path with s_name column."""
        from hta.common.timeline import align_module_with_kernels

        df = pd.DataFrame(
            {
                "index": [0, 1],
                "stream": [-1, 7],
                "ts": [100, 150],
                "dur": [100, 50],
                "name": ["aten::mm", "kernel"],  # string name column
                "first_kernel_start": [150, 150],
                "kernel_span": [50, 50],
                "num_kernels": [1, 0],
            }
        )
        result = align_module_with_kernels(df, ["aten::.*"])
        self.assertFalse(result.empty)

    def test_no_string_name_column_raises(self) -> None:
        """Lines 311-317: ValueError when neither name nor s_name is string."""
        from hta.common.timeline import align_module_with_kernels

        df = pd.DataFrame(
            {
                "index": [0],
                "stream": [-1],
                "ts": [100],
                "dur": [100],
                "name": [42],  # integer, not string
                "first_kernel_start": [150],
                "kernel_span": [50],
                "num_kernels": [1],
            }
        )
        with self.assertRaises(ValueError):
            align_module_with_kernels(df, ["aten::.*"])

    def test_include_original_cpu_events(self) -> None:
        """Lines 322-326: include_original_cpu_events=True branch."""
        from hta.common.timeline import align_module_with_kernels

        df = pd.DataFrame(
            {
                "index": [0, 1],
                "stream": [-1, 7],
                "ts": [100, 150],
                "dur": [100, 50],
                "name": ["aten::mm", "kernel"],  # string name column
                "first_kernel_start": [150, 150],
                "kernel_span": [50, 50],
                "num_kernels": [1, 0],
            }
        )
        result = align_module_with_kernels(
            df, ["aten::.*"], include_original_cpu_events=True
        )
        self.assertFalse(result.empty)


class TestPrepareTimelineEvents(unittest.TestCase):
    # AI-assisted test
    def test_empty_df(self) -> None:
        """Lines 361-363: empty DataFrame returns empty."""
        from hta.common.timeline import prepare_timeline_events

        result = prepare_timeline_events(pd.DataFrame())
        self.assertTrue(result.empty)

    def test_missing_required_columns(self) -> None:
        """Lines 368-372: missing required columns returns empty."""
        from hta.common.timeline import prepare_timeline_events

        df = pd.DataFrame({"foo": [1]})
        result = prepare_timeline_events(df)
        self.assertTrue(result.empty)

    def test_use_global_time(self) -> None:
        """Lines 417-423: use_global_time branch."""
        from hta.common.timeline import prepare_timeline_events, TimelinePlotSetting

        setting = TimelinePlotSetting(use_global_time=True, auto_detect=False)
        setting.event_type = __import__(
            "hta.common.timeline", fromlist=["EventType"]
        ).EventType.GPUEvents
        setting.multi_streams = True

        df = pd.DataFrame(
            {
                "name": ["op1", "op2"],
                "ts": [1000, 2000],
                "dur": [500, 100],
                "stream": [7, 7],
            }
        )
        result = prepare_timeline_events(df, setting=setting)
        self.assertFalse(result.empty)

    def test_no_amplify_short_events(self) -> None:
        """Lines 414-415: amplify_short_events=False branch."""
        from hta.common.timeline import prepare_timeline_events, TimelinePlotSetting

        setting = TimelinePlotSetting(amplify_short_events=False, auto_detect=False)
        setting.event_type = __import__(
            "hta.common.timeline", fromlist=["EventType"]
        ).EventType.GPUEvents
        setting.multi_streams = True

        df = pd.DataFrame(
            {
                "name": ["op1"],
                "ts": [1000],
                "dur": [500],
                "stream": [7],
            }
        )
        result = prepare_timeline_events(df, setting=setting)
        self.assertFalse(result.empty)


class TestPlotEventsTimeline(unittest.TestCase):
    # AI-assisted test
    def test_empty_events_returns_none(self) -> None:
        """Line 462: returns None when input is invalid."""
        from hta.common.timeline import plot_events_timeline

        result = plot_events_timeline("test", pd.DataFrame())
        self.assertIsNone(result)

    @patch("hta.common.timeline.px.timeline")
    def test_html_format(self, mock_px_timeline: Mock) -> None:
        """Lines 506-514: HTML plot format returns HTML string."""
        from hta.common.timeline import (
            plot_events_timeline,
            PlotFormat,
            TimelinePlotSetting,
        )

        mock_fig = Mock()
        mock_px_timeline.return_value = mock_fig
        mock_fig.data = []

        setting = TimelinePlotSetting(auto_detect=False, plot_format=PlotFormat.HTML)
        events = pd.DataFrame(
            {
                "calibrated_start_global": [100, 200],
                "calibrated_end_global": [150, 250],
                "task": ["t1", "t1"],
                "name": ["op1", "op2"],
                "dur": [50, 50],
            }
        )
        with patch(
            "hta.common.timeline.to_html", return_value="<html>"
        ) as mock_to_html:
            result = plot_events_timeline("test", events, setting=setting)
            mock_to_html.assert_called_once()
        self.assertEqual(result, "<html>")

    @patch("hta.common.timeline.px.timeline")
    def test_file_format_html(self, mock_px_timeline: Mock) -> None:
        """Lines 503-508: save to HTML file."""
        from hta.common.timeline import (
            plot_events_timeline,
            PlotFormat,
            TimelinePlotSetting,
        )

        mock_fig = Mock()
        mock_px_timeline.return_value = mock_fig
        mock_fig.data = []

        setting = TimelinePlotSetting(auto_detect=False, plot_format=PlotFormat.File)
        events = pd.DataFrame(
            {
                "calibrated_start_global": [100],
                "calibrated_end_global": [150],
                "task": ["t1"],
                "name": ["op1"],
                "dur": [50],
            }
        )
        with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as f:
            plot_events_timeline(
                "test", events, setting=setting, output_image_path=f.name
            )
            mock_fig.write_html.assert_called_once()

    @patch("hta.common.timeline.px.timeline")
    def test_file_format_image(self, mock_px_timeline: Mock) -> None:
        """Lines 506-507: save to image file."""
        from hta.common.timeline import (
            plot_events_timeline,
            PlotFormat,
            TimelinePlotSetting,
        )

        mock_fig = Mock()
        mock_px_timeline.return_value = mock_fig
        mock_fig.data = []

        setting = TimelinePlotSetting(auto_detect=False, plot_format=PlotFormat.File)
        events = pd.DataFrame(
            {
                "calibrated_start_global": [100],
                "calibrated_end_global": [150],
                "task": ["t1"],
                "name": ["op1"],
                "dur": [50],
            }
        )
        plot_events_timeline(
            "test", events, setting=setting, output_image_path="/tmp/test.png"
        )
        mock_fig.write_image.assert_called_once()


class TestTimelineClass(unittest.TestCase):
    # AI-assisted test
    def test_timeline_prepare_with_filter(self) -> None:
        """Lines 549-558: Timeline.prepare with filter_func."""
        from hta.common.timeline import Timeline, TimelinePlotSetting

        sym_table = TraceSymbolTable()
        sym_table.add_symbols(["op1", "kernel"])
        sym_id_map = sym_table.get_sym_id_map()

        df = pd.DataFrame(
            {
                "name": [sym_id_map["op1"]],
                "ts": [1000],
                "dur": [500],
                "stream": [7],
            }
        )
        setting = TimelinePlotSetting(auto_detect=False)
        setting.event_type = __import__(
            "hta.common.timeline", fromlist=["EventType"]
        ).EventType.GPUEvents
        setting.multi_streams = True

        mock_filter = Mock(return_value=df.copy())
        tl = Timeline(df, sym_table, filter_func=mock_filter, setting=setting)
        self.assertFalse(tl.timeline_events.empty)

    def test_timeline_is_timeline_events(self) -> None:
        """Lines 544-547: is_timeline_events static method."""
        from hta.common.timeline import Timeline, TimelinePlotSetting

        setting = TimelinePlotSetting()
        df = pd.DataFrame(
            {
                "task": ["t1"],
                "calibrated_start_global": [100],
                "calibrated_end_global": [200],
            }
        )
        self.assertTrue(Timeline.is_timeline_events(df, setting))


class TestFigNameConversions(unittest.TestCase):
    # AI-assisted test
    def test_get_fig_title_empty(self) -> None:
        """Line 520: empty fig_name defaults to 'untitled_figure'."""
        from hta.common.timeline import get_fig_title_from_fig_name

        result = get_fig_title_from_fig_name("")
        self.assertEqual(result, "Untitled Figure")

    def test_get_fig_name_empty(self) -> None:
        """Line 525: empty title defaults to 'Untitled Figure'."""
        from hta.common.timeline import get_fig_name_from_fig_title

        result = get_fig_name_from_fig_title("")
        self.assertEqual(result, "untitled_figure")


# ---- trace_diff.py tests ----


class TestLabeledTrace(unittest.TestCase):
    # AI-assisted test
    def test_no_trace_or_dir(self) -> None:
        """Lines 48-50: ValueError when neither t nor trace_dir provided."""
        from hta.trace_diff import LabeledTrace

        with self.assertRaises(ValueError):
            LabeledTrace(label="test")

    def test_invalid_trace_dir(self) -> None:
        """Lines 48-50: ValueError for invalid trace dir."""
        from hta.trace_diff import LabeledTrace

        with self.assertRaises(ValueError):
            LabeledTrace(label="test", trace_dir="/nonexistent/path")

    def test_default_label(self) -> None:
        """Line 43-44: auto-generated label when None."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(trace_dir=_vt_trace_dir())
        self.assertTrue(lt.label.startswith("t"))

    def test_extract_ops_with_rank_list(self) -> None:
        """Lines 110-112: extract_ops with rank as list."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        ranks = lt.ranks()
        if len(ranks) >= 1:
            ops = lt.extract_ops(rank=ranks[:1])
            self.assertFalse(ops.empty)

    def test_extract_ops_invalid_rank_type(self) -> None:
        """Lines 113-114: ValueError for invalid rank type."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        with self.assertRaises(ValueError):
            lt.extract_ops(rank="bad")  # type: ignore[arg-type]

    def test_extract_ops_invalid_rank_value(self) -> None:
        """Lines 116-118: ValueError for rank not in trace."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        with self.assertRaises(ValueError):
            lt.extract_ops(rank=999)

    def test_extract_ops_invalid_iteration_type(self) -> None:
        """Lines 131-133: ValueError for invalid iteration type."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        with self.assertRaises(ValueError):
            lt.extract_ops(iteration="bad")  # type: ignore[arg-type]

    def test_extract_ops_invalid_iteration_value(self) -> None:
        """Lines 135-137: ValueError for iteration not in trace."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        with self.assertRaises(ValueError):
            lt.extract_ops(iteration=999999)

    def test_extract_ops_no_ranks(self) -> None:
        """Lines 106-107: ValueError when trace has no ranks."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        lt.t.traces = {}
        with self.assertRaises(ValueError):
            lt.extract_ops()

    def test_extract_ops_no_iterations(self) -> None:
        """Lines 125-126: ValueError when no iterations available."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        lt.iteration_df = pd.DataFrame({"iteration": []})
        with self.assertRaises(ValueError):
            lt.extract_ops()

    def test_extract_ops_cpu_only(self) -> None:
        """Lines 154-155: DeviceType.CPU filtering."""
        from hta.trace_diff import DeviceType, LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        ops = lt.extract_ops(device_type=DeviceType.CPU)
        if not ops.empty:
            self.assertTrue(all(ops["stream"] == -1))

    def test_extract_ops_gpu_only(self) -> None:
        """Lines 156-157: DeviceType.GPU filtering."""
        from hta.trace_diff import DeviceType, LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        ops = lt.extract_ops(device_type=DeviceType.GPU)
        if not ops.empty:
            self.assertTrue(all(ops["stream"] != -1))

    def test_extract_ops_iteration_list(self) -> None:
        """Lines 130-131: iteration as list."""
        from hta.trace_diff import LabeledTrace

        lt = LabeledTrace(label="test", trace_dir=_vt_trace_dir())
        iters = lt.iterations()
        if iters:
            ops = lt.extract_ops(iteration=iters[:1])
            self.assertFalse(ops.empty)


class TestTraceArgumentAdapter(unittest.TestCase):
    # AI-assisted test
    def test_from_trace_dir(self) -> None:
        """Lines 219-220: construct from TraceDir string."""
        from hta.trace_diff import _trace_argument_adapter

        lt = _trace_argument_adapter(_vt_trace_dir(), "test_label")
        self.assertEqual(lt.label, "test_label")

    def test_from_trace_object(self) -> None:
        """Lines 221-222: construct from Trace object."""
        from hta.common.trace import Trace
        from hta.trace_diff import _trace_argument_adapter

        t = Trace(trace_dir=_vt_trace_dir())
        lt = _trace_argument_adapter(t, "test_label")
        self.assertEqual(lt.label, "test_label")

    def test_invalid_type(self) -> None:
        """Lines 225-226: ValueError for invalid type."""
        from hta.trace_diff import _trace_argument_adapter

        with self.assertRaises(ValueError):
            _trace_argument_adapter(42, "label")  # type: ignore[arg-type]


class TestTraceDiffVisualize(unittest.TestCase):
    # AI-assisted test
    @patch("hta.trace_diff.go.Figure")
    def test_visualize_counts_diff(self, mock_figure_class: Mock) -> None:
        """Lines 465-467: visualize_counts_diff."""
        from hta.trace_diff import TraceDiff

        mock_fig = Mock()
        mock_figure_class.return_value = mock_fig

        df = pd.DataFrame(
            {
                "Control_counts": [10, 5],
                "Test_counts": [12, 3],
                "Control_total_duration": [100, 50],
                "Test_total_duration": [120, 30],
                "diff_counts": [2, -2],
                "diff_duration": [20, -20],
            },
            index=pd.Index(["op1", "op2"]),
        )
        TraceDiff.visualize_counts_diff(df, show_image=False)
        mock_figure_class.assert_called_once()


class TestTraceDiffCompareTraces(unittest.TestCase):
    # AI-assisted test
    def test_same_label_renamed(self) -> None:
        """Lines 301-306: traces with same label get renamed."""
        from hta.trace_diff import LabeledTrace, TraceDiff

        vt_dir = _vt_trace_dir()
        lt1 = LabeledTrace(label="same", trace_dir=vt_dir)
        lt2 = LabeledTrace(label="same", trace_dir=vt_dir)
        result = TraceDiff.compare_traces(lt1, lt2)
        self.assertFalse(result.empty)


# ---- common/trace_call_stack.py tests ----


class TestCmpEventsWithZeroDuration(unittest.TestCase):
    # AI-assisted test
    def test_zero_vs_nonzero_close_end(self) -> None:
        """Line 44: zero event with non-zero CLOSE_END."""
        from hta.common.trace_call_stack import (
            _cmp_events_with_zero_duration,
            CLOSE_END,
            OPEN_END,
        )

        x = np.array([0, 0, OPEN_END, 100])
        y = np.array([1, 10, CLOSE_END, 100])
        result = _cmp_events_with_zero_duration(x, y)
        self.assertTrue(result)  # y is CLOSE_END → True

    def test_nonzero_vs_zero_open_end(self) -> None:
        """Line 46: non-zero with zero, x is OPEN_END."""
        from hta.common.trace_call_stack import _cmp_events_with_zero_duration, OPEN_END

        x = np.array([0, 10, OPEN_END, 100])
        y = np.array([1, 0, OPEN_END, 100])
        result = _cmp_events_with_zero_duration(x, y)
        self.assertTrue(result)

    def test_two_zeros_both_open(self) -> None:
        """Lines 48-49: two zero events, both OPEN_END."""
        from hta.common.trace_call_stack import _cmp_events_with_zero_duration, OPEN_END

        x = np.array([0, 0, OPEN_END, 100])
        y = np.array([1, 0, OPEN_END, 100])
        result = _cmp_events_with_zero_duration(x, y)
        self.assertTrue(result)  # x.index < y.index

    def test_two_zeros_both_close(self) -> None:
        """Lines 50-51: two zero events, both CLOSE_END."""
        from hta.common.trace_call_stack import (
            _cmp_events_with_zero_duration,
            CLOSE_END,
        )

        x = np.array([1, 0, CLOSE_END, 100])
        y = np.array([0, 0, CLOSE_END, 100])
        result = _cmp_events_with_zero_duration(x, y)
        self.assertTrue(result)  # x.index > y.index

    def test_two_zeros_one_open_one_close(self) -> None:
        """Lines 52-53: two zero events, one OPEN one CLOSE."""
        from hta.common.trace_call_stack import (
            _cmp_events_with_zero_duration,
            CLOSE_END,
            OPEN_END,
        )

        x = np.array([0, 0, OPEN_END, 100])
        y = np.array([1, 0, CLOSE_END, 100])
        result = _cmp_events_with_zero_duration(x, y)
        self.assertTrue(result)  # x is OPEN_END

    def test_both_nonzero_raises(self) -> None:
        """Lines 54-55: both non-zero raises ValueError."""
        from hta.common.trace_call_stack import _cmp_events_with_zero_duration, OPEN_END

        x = np.array([0, 5, OPEN_END, 100])
        y = np.array([1, 5, OPEN_END, 100])
        with self.assertRaises(ValueError):
            _cmp_events_with_zero_duration(x, y)


class TestLessThan(unittest.TestCase):
    # AI-assisted test
    def test_same_index_open_end(self) -> None:
        """Lines 70-71: same index, OPEN_END is smaller."""
        from hta.common.trace_call_stack import _less_than, CLOSE_END, OPEN_END

        x = np.array([5, 10, OPEN_END, 100])
        y = np.array([5, 10, CLOSE_END, 100])
        self.assertTrue(_less_than(x, y))  # OPEN_END < CLOSE_END

    def test_close_then_open(self) -> None:
        """Lines 76-77: x closing, y opening → True."""
        from hta.common.trace_call_stack import _less_than, CLOSE_END, OPEN_END

        x = np.array([0, 10, CLOSE_END, 100])
        y = np.array([1, 10, OPEN_END, 100])
        self.assertTrue(_less_than(x, y))

    def test_open_then_close(self) -> None:
        """Lines 79-80: x opening, y closing → False."""
        from hta.common.trace_call_stack import _less_than, CLOSE_END, OPEN_END

        x = np.array([0, 10, OPEN_END, 100])
        y = np.array([1, 10, CLOSE_END, 100])
        self.assertFalse(_less_than(x, y))

    def test_both_open_different_dur(self) -> None:
        """Lines 83-85: both OPEN_END, longer duration first."""
        from hta.common.trace_call_stack import _less_than, OPEN_END

        x = np.array([0, 20, OPEN_END, 100])
        y = np.array([1, 10, OPEN_END, 100])
        self.assertTrue(_less_than(x, y))  # longer dur is smaller

    def test_both_close_different_dur(self) -> None:
        """Lines 88-90: both CLOSE_END, shorter duration first."""
        from hta.common.trace_call_stack import _less_than, CLOSE_END

        x = np.array([0, 10, CLOSE_END, 100])
        y = np.array([1, 20, CLOSE_END, 100])
        self.assertTrue(_less_than(x, y))  # shorter dur is smaller

    def test_same_dur_open_end(self) -> None:
        """Lines 93-94: same dur, OPEN_END, smaller index first."""
        from hta.common.trace_call_stack import _less_than, OPEN_END

        x = np.array([0, 10, OPEN_END, 100])
        y = np.array([1, 10, OPEN_END, 100])
        self.assertTrue(_less_than(x, y))

    def test_same_dur_close_end(self) -> None:
        """Lines 95-96: same dur, CLOSE_END, larger index first."""
        from hta.common.trace_call_stack import _less_than, CLOSE_END

        x = np.array([1, 10, CLOSE_END, 100])
        y = np.array([0, 10, CLOSE_END, 100])
        self.assertTrue(_less_than(x, y))


class TestIsEventsSorted(unittest.TestCase):
    # AI-assisted test
    def test_unsorted_events(self) -> None:
        """Lines 123-127: detect unsorted events."""
        from hta.common.trace_call_stack import is_events_sorted, OPEN_END

        arr = np.array(
            [
                [1, 10, OPEN_END, 200],
                [0, 20, OPEN_END, 100],
            ]
        )
        self.assertFalse(is_events_sorted(arr))

    def test_sorted_events(self) -> None:
        """Lines 121-128: sorted events return True."""
        from hta.common.trace_call_stack import is_events_sorted, OPEN_END

        arr = np.array(
            [
                [0, 20, OPEN_END, 100],
                [1, 10, OPEN_END, 200],
            ]
        )
        self.assertTrue(is_events_sorted(arr))


class TestCallStackGraphInit(unittest.TestCase):
    # AI-assisted test
    def test_gpu_device_type_returns(self) -> None:
        """Lines 227-231: GPU device type logs error and returns."""
        from hta.common.trace_call_stack import CallStackGraph, CallStackIdentity

        identity = CallStackIdentity(rank=0, pid=100, tid=200)
        # All streams > 0 → GPU device type
        df = pd.DataFrame(
            {
                "index": [0, 1],
                "stream": [7, 7],
                "ts": [100, 200],
                "dur": [50, 50],
            }
        )
        full_df = df.copy()
        full_df["end"] = full_df["ts"] + full_df["dur"]
        correlation = pd.DataFrame({"cpu_index": [], "gpu_index": []})
        sym_table = TraceSymbolTable()

        # This should not crash — just returns early for GPU threads
        csg = CallStackGraph(
            df,
            identity,
            correlation,
            full_df,
            sym_table,
            use_existing_stack_columns=False,
            save_call_stack_to_df=False,
        )
        self.assertIsNotNone(csg)


class TestCallStackGraphMethods(unittest.TestCase):
    # AI-assisted test
    def _make_simple_graph(self):
        """Helper: create a simple CallStackGraph from CPU events."""
        from hta.common.trace_call_stack import CallStackGraph, CallStackIdentity

        identity = CallStackIdentity(rank=0, pid=100, tid=200)
        df = pd.DataFrame(
            {
                "index": [0, 1, 2],
                "stream": [-1, -1, -1],
                "ts": [100, 110, 200],
                "dur": [150, 20, 50],
                "index_correlation": [-1, -1, -1],
                "correlation": [-1, -1, -1],
            }
        )
        full_df = df.copy()
        full_df["end"] = full_df["ts"] + full_df["dur"]
        full_df["parent"] = pd.array([pd.NA, pd.NA, pd.NA], dtype=pd.Int64Dtype())
        full_df["depth"] = pd.array([pd.NA, pd.NA, pd.NA], dtype=pd.Int16Dtype())
        full_df["height"] = pd.array([pd.NA, pd.NA, pd.NA], dtype=pd.Int16Dtype())
        full_df["num_kernels"] = pd.array([0, 0, 0], dtype=pd.Int32Dtype())
        full_df["kernel_dur_sum"] = pd.array([0, 0, 0], dtype=pd.Int64Dtype())
        full_df["kernel_span"] = pd.array([0, 0, 0], dtype=pd.Int64Dtype())
        full_df["first_kernel_start"] = pd.array([0, 0, 0], dtype=pd.Int64Dtype())
        full_df["last_kernel_end"] = pd.array([0, 0, 0], dtype=pd.Int64Dtype())

        correlation = pd.DataFrame(
            {"cpu_index": pd.Series(dtype=int), "gpu_index": pd.Series(dtype=int)}
        )
        sym_table = TraceSymbolTable()

        csg = CallStackGraph(
            df,
            identity,
            correlation,
            full_df,
            sym_table,
            use_existing_stack_columns=False,
            save_call_stack_to_df=True,
        )
        return csg

    def test_get_parent_nonexistent(self) -> None:
        """Lines 506-508: get_parent for nonexistent node."""
        csg = self._make_simple_graph()
        result = csg.get_parent(99999)
        self.assertEqual(result, -2)  # NON_EXISTENT_NODE_INDEX

    def test_get_children_nonexistent(self) -> None:
        """Lines 519-521: get_children for nonexistent node."""
        csg = self._make_simple_graph()
        result = csg.get_children(99999)
        self.assertEqual(result, [])

    def test_get_root(self) -> None:
        """Lines 532-538: get_root traverses to root."""
        csg = self._make_simple_graph()
        root = csg.get_root(0)
        self.assertTrue(root < 0)  # Root should be a negative index

    def test_get_root_nonexistent(self) -> None:
        """Line 532-533: get_root for nonexistent node returns NULL_NODE_INDEX."""
        csg = self._make_simple_graph()
        result = csg.get_root(99999)
        self.assertEqual(result, -1)  # NULL_NODE_INDEX

    def test_get_path_to_root(self) -> None:
        """Lines 549-560: get_path_to_root."""
        csg = self._make_simple_graph()
        # Node 1 is child of node 0
        path = csg.get_path_to_root(1)
        self.assertIn(1, path)
        self.assertTrue(len(path) >= 2)

    def test_get_path_to_root_nonexistent(self) -> None:
        """Line 549-550: nonexistent node returns empty list."""
        csg = self._make_simple_graph()
        path = csg.get_path_to_root(99999)
        self.assertEqual(path, [])

    def test_get_paths_to_leaves(self) -> None:
        """Lines 575-594: get_paths_to_leaves."""
        csg = self._make_simple_graph()
        root_idx = csg.root_index
        paths = csg.get_paths_to_leaves(root_idx)
        self.assertTrue(len(paths) >= 1)

    def test_get_leaf_nodes(self) -> None:
        """Lines 596-606: get_leaf_nodes."""
        csg = self._make_simple_graph()
        leaves = csg.get_leaf_nodes(csg.root_index)
        self.assertTrue(len(leaves) >= 1)

    def test_get_descendants(self) -> None:
        """Lines 608-621: get_descendants."""
        csg = self._make_simple_graph()
        desc = csg.get_descendants(csg.root_index)
        self.assertTrue(len(desc) >= 1)

    def test_get_dataframe(self) -> None:
        """Line 624: get_dataframe returns df."""
        csg = self._make_simple_graph()
        df = csg.get_dataframe()
        self.assertFalse(df.empty)

    def test_repr(self) -> None:
        """Lines 271-278: __repr__."""
        csg = self._make_simple_graph()
        s = repr(csg)
        self.assertIn("CallStackGraph", s)

    def test_get_depth(self) -> None:
        """Lines 750-758: get_depth."""
        csg = self._make_simple_graph()
        depth = csg.get_depth()
        self.assertFalse(depth.empty)

    def test_dfs_traverse(self) -> None:
        """Lines 870-887: dfs_traverse with callbacks."""
        csg = self._make_simple_graph()
        entered = []
        exited = []

        def enter_fn(nid, node):
            entered.append(nid)

        def exit_fn(nid, node):
            exited.append(nid)

        csg.dfs_traverse(enter_fn, exit_fn)
        self.assertTrue(len(entered) > 0)
        self.assertEqual(len(entered), len(exited))


class TestCallStackGraphHasValidStackColumns(unittest.TestCase):
    # AI-assisted test
    def test_missing_stack_columns(self) -> None:
        """Lines 289-291: missing parent/depth/height columns → False."""
        from hta.common.trace_call_stack import CallStackGraph

        df = pd.DataFrame({"index": [0], "stream": [-1], "ts": [100], "dur": [50]})
        full_df = df.copy()
        full_df["end"] = full_df["ts"] + full_df["dur"]
        # No parent/depth/height columns — _has_valid_stack_columns returns False
        csg = CallStackGraph.__new__(CallStackGraph)
        csg.full_df = full_df
        csg.df = df
        result = csg._has_valid_stack_columns()
        self.assertFalse(result)

    def test_all_parent_minus_one(self) -> None:
        """Lines 300-302: parent all -1 → False."""
        from hta.common.trace_call_stack import CallStackGraph

        csg = CallStackGraph.__new__(CallStackGraph)
        full_df = pd.DataFrame(
            {
                "index": [0, 1],
                "stream": [-1, -1],
                "ts": [100, 200],
                "dur": [50, 50],
                "parent": [-1, -1],
                "depth": [0, 0],
                "height": [0, 0],
            }
        )
        csg.full_df = full_df
        csg.df = full_df
        result = csg._has_valid_stack_columns()
        self.assertFalse(result)


class TestCallStackGraphUpdateParent(unittest.TestCase):
    # AI-assisted test
    def test_update_parent_invalid_parent(self) -> None:
        """Lines 471-472: ValueError when new_parent_index not in nodes."""
        from hta.common.trace_call_stack import CallStackGraph

        csg = CallStackGraph.__new__(CallStackGraph)
        csg.nodes = {}
        with self.assertRaises(ValueError):
            csg._update_parent([0], 999)

    def test_update_parent_of_first_layer_invalid(self) -> None:
        """Lines 442-445: ValueError when new_parent_index not in nodes or full_df."""
        from hta.common.trace_call_stack import CallStackGraph

        csg = CallStackGraph.__new__(CallStackGraph)
        csg.nodes = {}
        with self.assertRaises(ValueError):
            csg.update_parent_of_first_layer_nodes(999)


class TestCallStackGraphSaveToDf(unittest.TestCase):
    # AI-assisted test
    def test_save_call_stack_gpu_returns(self) -> None:
        """Lines 704-705: _save_call_stack_to_df returns early for GPU."""
        from hta.common.trace_call_stack import CallStackGraph
        from hta.common.types import DeviceType

        csg = CallStackGraph.__new__(CallStackGraph)
        csg.device_type = DeviceType.GPU
        csg._save_call_stack_to_df()  # Should not raise

    def test_save_call_stack_no_parent_col(self) -> None:
        """Lines 706-708: _save_call_stack_to_df returns early if no parent column."""
        from hta.common.trace_call_stack import CallStackGraph
        from hta.common.types import DeviceType

        csg = CallStackGraph.__new__(CallStackGraph)
        csg.device_type = DeviceType.CPU
        csg.full_df = pd.DataFrame({"index": [0]})
        csg._save_call_stack_to_df()  # Should not raise


class TestCallStackGraphAddKernelInfo(unittest.TestCase):
    # AI-assisted test
    def test_no_num_kernels_column(self) -> None:
        """Lines 778-780: _add_kernel_info_to_cpu_ops returns early if no num_kernels col."""
        from hta.common.trace_call_stack import CallStackGraph

        csg = CallStackGraph.__new__(CallStackGraph)
        csg.full_df = pd.DataFrame({"index": [0]})
        csg._add_kernel_info_to_cpu_ops()  # Should not raise


if __name__ == "__main__":
    unittest.main()
